"""Add initial models

Revision ID: 322e5e9970b8
Revises:
Create Date: 2025-12-20 23:32:41.791478

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "322e5e9970b8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email_hash", sa.String(length=60), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("device_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_seen", sa.TIMESTAMP(), nullable=False),
        sa.Column("bio", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_email_lookup", "users", ["email_hash"], unique=False)
    op.create_index("idx_username_lookup", "users", ["username"], unique=False)
    op.create_index(op.f("ix_users_email_hash"), "users", ["email_hash"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "pendingmessages",
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("encrypted_payload", sa.LargeBinary(), nullable=False),
        sa.Column("message_type", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_expires_at", "pendingmessages", ["expires_at"], unique=False)
    op.create_index("idx_recipient_messages", "pendingmessages", ["recipient_id", "created_at"], unique=False)
    op.create_index(op.f("ix_pendingmessages_recipient_id"), "pendingmessages", ["recipient_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pendingmessages_recipient_id"), table_name="pendingmessages")
    op.drop_index("idx_recipient_messages", table_name="pendingmessages")
    op.drop_index("idx_expires_at", table_name="pendingmessages")
    op.drop_table("pendingmessages")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email_hash"), table_name="users")
    op.drop_index("idx_username_lookup", table_name="users")
    op.drop_index("idx_email_lookup", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
